baseURL: "https://otters-tech.github.io" 
title: Otter Tech
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
        - name: News
          url: news/
          weight: 1 
        - name: Projects
          url: projects/
          weight: 2
        # - name: Courses
        #   url: courses/
        #   weight: 3
        - name: Papers
          url: papers/
          weight: 3 
        - name: People
          url: people/
          weight: 4
        - name: Contact
          url: contact/
          weight: 5

params:
    description: "Technology that feels human. We design and ship AI powered solutions that make life easier, decisions clearer, and services more inclusive."
    author: Otter Tech Limited
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["projects","courses","papers","news"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Otter Tech
          subtitle: "Technology that feels human. We design and ship AI powered solutions that make life easier, decisions clearer, and services more inclusive.✨"
          imageUrl: "icon.png"
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: News
              url: news/
            - name: Projects
              url: projects/
            # - name: Courses
            #   url: courses/
            - name: Papers
              url: papers/
            - name: People
              url: people/
            - name: Contact
              url: contact/

    socialIcons:
        - name: GitHub
          url: https://otters-tech.github.io
        - name: YouTube
          url: https://otters-tech.github.io
        - name: Twitter
          url: https://otters-tech.github.io
        - name: Email
          url: otterstanding@gmail.com

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Otter Tech"
      icon: "icon.png"
      iconHeight: 40

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2

outputs:
    home: ["HTML", "RSS"]
    section: ["HTML", "RSS"]
    taxonomy: ["HTML", "RSS"]
    term: ["HTML", "RSS"]
