baseURL: "https://pascalmichaillat.org/hugo-website/" 
title: Otter Tech Limited
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
        - name: News
          url: news/
          weight: 5 
        - name: Projects
          url: projects/
          weight: 2
        - name: Courses
          url: courses/
          weight: 3
        - name: Papers
          url: papers/
          weight: 4 
        - name: People
          url: people/
          weight: 6
        - name: Contact
          url: contact/
          weight: 7

params:
    description: "This website hosts Moritz-Maria von Igelfeld's research papers, books, course materials, data, curriculum vitae, and contact information."
    author: Otter Tech Limited
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["projects","courses","papers","news"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Otter Tech
          subtitle: "Technology that feels human. We design and ship AI powered solutions that make life easier, decisions clearer, and services more inclusive.✨"
          imageUrl: "icon.png"
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: Projects
              url: projects/
            - name: Courses
              url: courses/
            - name: Papers
              url: paper/
            - name: News
              url: news/
            - name: People
              url: people/
            - name: Contact
              url: contact/

    socialIcons:
        - name: GitHub
          url: https://github.com/pmichaillat
        - name: YouTube
          url: https://www.youtube.com/@pmichaillat
        - name: Twitter
          url: https://x.com/pmichaillat
        - name: Email
          url: otterstanding@gmail.com

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Otter Tech"
      icon: "icon.png"
      iconHeight: 40

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2